trigger:
  branches:
    include:
    - main
    - feature/*
  paths:
    exclude:
    - README.md

resources:
  repositories:
    - repository: templates
      type: git
      name: platform/Pipeline.Environment

variables:
- name: resourceGroupLocation
  value: northeurope
- name: testAzureServiceConnection
  value: Devops - Deploy
- name: prodAzureServiceConnection
  value: Devops - Deploy
- name: brokerName
  value: events003

extends:
  template: pipeline/broker-pipeline.yml@templates
  parameters:
    parametersDirectory: remotecall/broker/parameters
    environments:  
    - environmentName: ft
      azureServiceConnection:  ${{ variables.testAzureServiceConnection }}
      resourceGroupName: ft-${{ variables.brokerName }}-rg
      resourceGroupLocation: ${{ variables.resourceGroupLocation }}
      parametersFile:  ft.parameters.json
    - environmentName: it
      azureServiceConnection:  ${{ variables.testAzureServiceConnection }}
      resourceGroupName: it-${{ variables.brokerName }}-rg
      resourceGroupLocation: ${{ variables.resourceGroupLocation }}
      parametersFile:  it.parameters.json
    - environmentName: pr
      azureServiceConnection:  ${{ variables.prodAzureServiceConnection }}
      resourceGroupName: pr-${{ variables.brokerName }}-rg
      resourceGroupLocation: ${{ variables.resourceGroupLocation }}
      parametersFile:  pr.parameters.json