parameters:
- name: parametersDirectory
  type: string
- name: templateFile
  type: string


jobs:
- job:
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: steps/ci-steps-remote.yml
    parameters:
      parametersDirectory: ${{ parameters.parametersDirectory }}

- job:
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: steps/ci-steps-local.yml
    parameters:
      templateFile: ${{ parameters.templateFile }}
